QUERY_PARAM_LANG = "lang:"

QUERY_PARAM_TIME = "time:"
QUERY_PARAM_GMT = "gmt:"
QUERY_PARAM_TZNAME = "tzname:"


MODIFIER_PARAMS = [
    QUERY_PARAM_LANG
]

RESULT_PARAMS = [
    QUERY_PARAM_TIME,
    QUERY_PARAM_GMT,
    QUERY_PARAM_TZNAME
]

ALL_PARAMS = MODIFIER_PARAMS + RESULT_PARAMS
